#!/usr/bin/env python
# -*- coding: utf-8 -*-
# -----------------------------------------------

from settings import settings


class AppConfig:

    # ------ APPLICATION ------
    ENV = settings.ENV
    DEBUG = settings.DEBUG
    TESTING = settings.TESTING
    SERVER_NAME = settings.SERVER_NAME
    APPLICATION_ROOT = settings.APPLICATION_ROOT
    PREFERRED_URL_SCHEME = settings.PREFERRED_URL_SCHEME
    
    # ------ COOKIE ------
    SECRET_KEY = settings.SECRET_KEY
    PERMANENT_SESSION_LIFETIME = settings.PERMANENT_SESSION_LIFETIME
    SESSION_COOKIE_NAME = settings.SESSION_COOKIE_NAME
    SESSION_COOKIE_DOMAIN = settings.SESSION_COOKIE_DOMAIN
    SESSION_COOKIE_PATH = settings.SESSION_COOKIE_PATH
    SESSION_COOKIE_HTTPONLY = settings.SESSION_COOKIE_HTTPONLY
    SESSION_COOKIE_SECURE = settings.SESSION_COOKIE_SECURE
    SESSION_COOKIE_SAMESITE = settings.SESSION_COOKIE_SAMESITE
    SESSION_REFRESH_EACH_REQUEST = settings.SESSION_REFRESH_EACH_REQUEST
    MAX_COOKIE_SIZE = settings.MAX_COOKIE_SIZE

    # ------ CONTENT ------
    BASEDIR = settings.BASEDIR
    MAX_CONTENT_LENGTH = settings.MAX_CONTENT_LENGTH
    JSON_AS_ASCII = settings.JSON_AS_ASCII
    JSON_SORT_KEYS = settings.JSON_SORT_KEYS
    JSONIFY_PRETTYPRINT_REGULAR = settings.JSONIFY_PRETTYPRINT_REGULAR
    JSONIFY_MIMETYPE = settings.JSONIFY_MIMETYPE
    TEMPLATES_AUTO_RELOAD = settings.TEMPLATES_AUTO_RELOAD

    # ------ OTHER ------
    PROPAGATE_EXCEPTIONS = settings.PROPAGATE_EXCEPTIONS
    PRESERVE_CONTEXT_ON_EXCEPTION = settings.PRESERVE_CONTEXT_ON_EXCEPTION
    USE_X_SENDFILE = settings.USE_X_SENDFILE
    SEND_FILE_MAX_AGE_DEFAULT = settings.SEND_FILE_MAX_AGE_DEFAULT
    TRAP_BAD_REQUEST_ERRORS = settings.TRAP_BAD_REQUEST_ERRORS
    TRAP_HTTP_EXCEPTIONS = settings.TRAP_HTTP_EXCEPTIONS
    EXPLAIN_TEMPLATE_LOADING = settings.EXPLAIN_TEMPLATE_LOADING

